### ISSUE TITLE
"Program: not v4 or newer irriation component" despite v5 of integration and card

### ISSUE THREAD

**Issue by gdgeist** [petergridge/Irrigation-Card#2]
-->
Card displays the message "Program: not v4 or newer irriation component" despite v5 of integration and card

Environment
Home Assistant 2023.6.1
Supervisor 2023.06.1

Steps to reproduce
1. Install irrigation integration via HACS
2.  Restart Home Assistant
3.  Install irrigation card via HACS
4. Configure program
5. configure dashboard card

**Comment by petergridge** [comment]
Hi,

Can you send me a screen shot of the attributes from the irrigation program, you can get this from the developer tools.

It would also be helpful to have screenshots from the irrigation program configuration.

This error should only occur if there a no zones configured, i.e. the zone_count attribute is missing or 0.

**Comment by FrcJules** [comment]
![Screenshot from 2023-07-02 01-59-57](https://github.com/petergridge/Irrigation-Card/assets/114910682/4e16ccd2-031d-4ccd-be7f-36d2a606e005)

**Comment by petergridge** [comment]
Hi Do you have any  errors in the log?
