### ISSUE TITLE
Suggestion. Change group visualitation

### ISSUE THREAD

**Issue by kikorr** [petergridge/Irrigation-Card#3]
Suggestion. When creating a group, you could generate a group name so that the card would show: "group name" "zone". So if you make a very large group of zones you do not unbalance the card.

In my example I only use 4 zones in this group, but if they were more it would be visually complicated to see everything.

![image](https://github.com/petergridge/Irrigation-Card/assets/708794/08218aa2-9a2d-4faf-ac39-33a9271431f8)

Same will apply to Zone, I think it would be usefull to be able to change de name of the zone.

Finally, it will be awesome if in the group you can select only one water timer and if you want to irrigate all at the same time o secuentially. Example of secuentially, if yo select 3 min of watering, then all the zones will spend 3 min of watering. If there are 3 zones, it will be 9 min. 
If you select in the same example 3 min for 3 zones but not secuentially,  will be watering for only 3 min all the zones at the same time.

Cheers.

**Comment by petergridge** [comment]
Hi,

I have not been particularly happy with the group functionality and was planning to revisit it.

I am thinking of removing the group feature altogether as it can be accomplished by creating a switch group helper. This allows multiple switches to be grouped and behave as a single switch.
![image](https://github.com/petergridge/Irrigation-Card/assets/40281772/502717b7-08d5-48bb-85ed-ab7e3ceff71b)

This will remove some functionality as all the switches will share a single set of parameters, but I think it will support most users. I think the existing model is a level of complication that is not really required.

The new approach has some benefits though, it reduces the complexity of the code, simplifies the Config Flow when setting up the program and will make the Card more readable.

Will this support your need, this approach will work now if you want to try.

For the watering time, I am not planning to change the existing approach where it is applied to each zone.

**Comment by kikorr** [comment]
Wow! With groups works perfect.

Thanks for the tip.
