### ISSUE TITLE
When irrigation time is set to 0 next run and last run are not showed

### ISSUE THREAD

**Issue by clmun** [petergridge/Irrigation-Card#5]
Hello

I linked the input time duration with another entity (the calculated value from smart irrigation) and for the days when the irrigation should not run this input is set to 0.

Now, irrigation is set to start at 6:05 am and my expectations were to see last run (date from yesterday when irrigation was last done) and next run (date from tomorrow), but instead it shows like this:
![image](https://github.com/petergridge/Irrigation-Card/assets/16850783/7b05f135-84c7-48f9-9e5b-f4cb333531a6)

Can we have some work around to see the last and next run correctly?

Thank you

**Comment by clmun** [comment]
Actually after a manual switch I get the card correct:
![image](https://github.com/petergridge/Irrigation-Card/assets/16850783/a6fa3bc1-cba7-42fa-90e4-52256e4caf00)

So issue is when time for irrigation is on and if it is 0 it shows like in 1st picture.

**Comment by petergridge** [comment]
I have have not handled run time of 0 very well. I was not expecting that use case, I will look at how I can represent it better. I will probably treat the same as a disabled zone.
