### ISSUE TITLE
card error (Can not read properties of undefined (reading 'attributes'))

### ISSUE THREAD

**Issue by L0bit0** [petergridge/Irrigation-Card#6]
Hi

NOTE: I opened another issue on the integration page as i feel it is not working since last integration update.

Issue:
- Card is giving an error:
![image](https://github.com/user-attachments/assets/20eda2c0-46fa-4979-bf1a-ee84e468bd32)
- Card is properly showed on ipad App :-)
        - iPad
                ![image](https://github.com/user-attachments/assets/1fb86beb-f1b7-423a-80ad-dc4bb2f2991c)
        - Web
                 ![image](https://github.com/user-attachments/assets/c3c1431d-02e3-4057-9f2f-baf3caab8d96)
- Irrigation schedule looks is still working fine
- When I try to edit the card i see this:
![image](https://github.com/user-attachments/assets/19d28ff4-de23-4069-b666-4080bf8e9d47)
    - yaml:
```
type: custom:irrigation-card
program: switch.riego_no
entities: []
show_program: true
next_run_label: Next Run
last_ran_label: Last Run
remaining_label: Remaining time
```
- I tried to manually edit and add the switches but still do not work:
![image](https://github.com/user-attachments/assets/b82ac8b5-03c0-46be-a4ee-69adee77311b)
```
type: custom:irrigation-card
program: switch.riego_no
entities:
  - switch.valvula_riego_1_switch
  - switch.valvula_riego_2_switch
show_program: true
next_run_label: Next Run
last_ran_label: Last Run
remaining_label: Remaining time
```

- I reconfigure the zones, but still failing
- I confirmed valves and switches works fine.

Thanks

**Comment by petergridge** [comment]
Hi, you shouldn't need to have this version installed unless the auto install does not work. I recommend uninstalling this version and using the card auto installed with the component.

**Comment by L0bit0** [comment]
@petergridge thanks, but I feel I duplicated this as I did do not know if the problem was on the card or on the integration (I indicate at the beguining of the post...)

Thanks for your help and sorry for the confusion
