### ISSUE TITLE
All cards shows "invalid entity ID at position 1: undefined

### ISSUE THREAD

**Issue by L0bit0** [petergridge/Irrigation-Card#7]
Hi

since days ago, I have all my irrigation cards like this: 
![image](https://github.com/user-attachments/assets/ef4b7a38-91f7-4466-be1c-9787873b0387)

I have confirmed, and all entities are created and ok, I did not remove any of them:
![image](https://github.com/user-attachments/assets/32d51055-22c8-48f4-bcb9-310879ce9db8)

I restarted home assistant and browsers several times.

I am not sure when was the last time cards where showed ok, summer is ending so i do not review irrigation cards often... 

Versions:
- HA 2024.9.3
- irrigation component: V2024.09.05
- irrigation card: 2024.09.07
Full card screenshot:
![image](https://github.com/user-attachments/assets/3e3d40cd-3e90-4c03-afb5-9f65e240e0e6)

Any idea?  thanks

**Comment by petergridge** [comment]
Try updating to 2024.09.07 of the custom component

**Comment by nickushorul** [comment]
i have the same problem !

**Comment by petergridge** [comment]
Hi, 

can you verify if you have one or both of these items in your resources?
<img width="582" alt="image" src="https://github.com/user-attachments/assets/c0495545-5e98-4661-8a10-d8fa7bf9b201">
<img width="655" alt="image" src="https://github.com/user-attachments/assets/b4062ab4-f0ef-44a5-bf8d-9cfee1c78a5a">

<img width="656" alt="image" src="https://github.com/user-attachments/assets/5ae1fb85-d216-4926-a996-8680ea8dcb8c">

**Comment by L0bit0** [comment]
yes, it is working with 2024.09.05

I assume this will be fixied on future releases. correct?

About component, this is what i have regarding irrigation:
![image](https://github.com/user-attachments/assets/95dbb3ea-a0f0-4f03-823a-195b6dbf4e0f)

But i had already downgraded the main component.

I can try to upgrade and check again if you need... it does not take that much.

Thanks in advance.

**Comment by petergridge** [comment]
Hi, 

You do not need to have the custom card install. The card is install automatically with each release of the component.

I recommend:
1. Delete the custom card and the HACS repository from your installation.
2. Ensure the hacsfiles/irrigation-card/... resource is removed, delete it if required
3. Upgrade to the latest version of the component V2024.10.01
4. Restart HA
5. Refresh the browser (you may need to clear the browser cache)
6. Add the card to your HA Dashboard
The card will be upgraded with each install of the component.

**Comment by petergridge** [comment]
Please let me know if this process worked for you.

Cheers
Pete

**Comment by L0bit0** [comment]
Done

FYI: i had to manually remove the irrigation card resource (step 2)

All looks good, old cards are working: 
![image](https://github.com/user-attachments/assets/9b9ecfa3-c49f-49ac-b3b8-a1673467cf8d)

thanks!!

**Comment by petergridge** [comment]
Thanks for letting me know.
